name: 'Install dependencies with pnpm'
description: 'Checks out the codebase, sets up Node, pnpm, installs dependencies, and manages a cache.'
inputs:
  checkout-fetch-depth:
    description: 'Number of commits to fetch. 0 indicates all history for all branches and tags.'
    required: false
    default: '1'
runs:
  using: "composite"
  steps:
    - name: Checkout the codebase
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.checkout-fetch-depth }}
    - name: Setup pnpm
      uses: pnpm/action-setup@v2.2.4
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: ".node-version"
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
